# Site settings
title: g33k.st
email: antoinebsr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Curated creative output, bridging the gap between hip hop and technology.
  Featuring music, art and apps for the urban hacker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://g33k.st" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['/bower_components']
